name: package_storage
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  responsive_sizer: ^3.1.1
  flutter_bloc: ^8.1.2
  page_transition: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/
  
  fonts:
    - family: Rubik
      fonts:
        - asset: "assets/fonts/Rubik-Light.ttf"
          weight: 300
        - asset: "assets/fonts/Rubik-Regular.ttf"
          weight: 400
        - asset: "assets/fonts/Rubik-Medium.ttf"
          weight: 500
        - asset: "assets/fonts/Rubik-SemiBold.ttf"
          weight: 600
        - asset: "assets/fonts/Rubik-Bold.ttf"
          weight: 700
        - asset: "assets/fonts/Rubik-ExtraBold.ttf"
          weight: 800
        - asset: "assets/fonts/Rubik-Black.ttf"
          weight: 900
